steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'clean']
  - name: node
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'SESSION_SECRET=${_SESSION_SECRET}'
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
