steps:
  - name: node:18
    entrypoint: node
    args: ['--version']
  - name: node:18
    entrypoint: npm
    args: ['install']
  - name: node:18
    entrypoint: npm
    args: ['run', 'test']
  - name: node:18
    entrypoint: npm
    args: ['run', 'clean']
  - name: node:18
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'API_URL=${_API_URL}'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - 'GITHUB_CLIENT_ID=${_GITHUB_CLIENT_ID}'
      - 'GITHUB_CLIENT_SECRET=${_GITHUB_CLIENT_SECRET}'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - 'NOREPLY_EMAIL_PASSWORD=${_NOREPLY_EMAIL_PASSWORD}'
      - 'NOREPLY_EMAIL_USER=${_NOREPLY_EMAIL_USER}'
      - 'NOTION_TOKEN=${_NOTION_TOKEN}'
      - 'NOTION_ONBOARDING_PAGE_ID=${_NOTION_ONBOARDING_PAGE_ID}'
      - 'NOTION_WAITLIST_PAGE_ID=${_NOTION_WAITLIST_PAGE_ID}'
      - 'INTEGRATION_TEST_URL=${_INTEGRATION_TEST_URL}'
      - 'SERVER_LOGS_URL=${_SERVER_LOGS_URL}'
      - 'GCLOUD_STORAGE_BUCKET=${_GCLOUD_STORAGE_BUCKET}'
      - 'GOOGLE_SEARCH_CONSOLE_URL=${_GOOGLE_SEARCH_CONSOLE_URL}'
      - 'GOOGLE_ANALYTICS_REPORTS_URL=${_GOOGLE_ANALYTICS_REPORTS_URL}'
      - 'GOOGLE_ANALYTICS_DASHBOARD_URL=${_GOOGLE_ANALYTICS_DASHBOARD_URL}'
      - 'GOOGLE_ANALYTICS_API_SECRET=${_GOOGLE_ANALYTICS_API_SECRET}'
      - 'GOOGLE_ANALYTICS_MEASUREMENT_ID=${_GOOGLE_ANALYTICS_MEASUREMENT_ID}'
      - 'NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=${_NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID}'
      - 'NEXT_PUBLIC_COOKIE_DOMAIN=${_NEXT_PUBLIC_COOKIE_DOMAIN}'
      - 'NEXT_PUBLIC_COOKIE_NAME=${_NEXT_PUBLIC_COOKIE_NAME}'
      - 'NEXT_PUBLIC_DOCS_URL=${_NEXT_PUBLIC_DOCS_URL}'
  - name: node:18
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
